USE [master]
GO

/****** Object:  Database [SWCCorp]    Script Date: 7/8/2016 12:31:38 PM ******/
CREATE DATABASE [SWCCorp]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SWCCorp', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQL2014\MSSQL\DATA\SWCCorp.mdf' , SIZE = 3264KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'SWCCorp_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQL2014\MSSQL\DATA\SWCCorp_log.ldf' , SIZE = 832KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [SWCCorp] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SWCCorp].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SWCCorp] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SWCCorp] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SWCCorp] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SWCCorp] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SWCCorp] SET ARITHABORT OFF 
GO

ALTER DATABASE [SWCCorp] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [SWCCorp] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SWCCorp] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SWCCorp] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SWCCorp] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SWCCorp] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SWCCorp] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SWCCorp] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SWCCorp] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SWCCorp] SET  ENABLE_BROKER 
GO

ALTER DATABASE [SWCCorp] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SWCCorp] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SWCCorp] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SWCCorp] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SWCCorp] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SWCCorp] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SWCCorp] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SWCCorp] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [SWCCorp] SET  MULTI_USER 
GO

ALTER DATABASE [SWCCorp] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SWCCorp] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SWCCorp] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SWCCorp] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [SWCCorp] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SWCCorp] SET  READ_WRITE 
GO

